; pal/blk packets
; SetPalFunctions indexes (see engine/gfx/palettes.asm)
	const_def
	const SET_PAL_BATTLE_BLACK         ; $00
	const SET_PAL_BATTLE               ; $01
	const SET_PAL_TOWN_MAP             ; $02
	const SET_PAL_STATUS_SCREEN        ; $03
	const SET_PAL_POKEDEX              ; $04
	const SET_PAL_SLOTS                ; $05
	const SET_PAL_TITLE_SCREEN         ; $06
	const SET_PAL_NIDORINO_INTRO       ; $07
	const SET_PAL_GENERIC              ; $08
	const SET_PAL_OVERWORLD            ; $09
	const SET_PAL_PARTY_MENU           ; $0A
	const SET_PAL_POKEMON_WHOLE_SCREEN ; $0B
	const SET_PAL_GAME_FREAK_INTRO     ; $0C
	const SET_PAL_TRAINER_CARD         ; $0D
	const SET_PAL_OAK_INTRO            ; $0E
	const SET_PAL_NAMING_SCREEN        ; $0F
	const SET_PAL_BATTLE_AFTER_BLACK   ; $10

DEF SET_PAL_PARTY_MENU_HP_BARS EQU $fc
DEF SET_PAL_DEFAULT EQU $ff

; sgb palettes
; SuperPalettes indexes (see data/sgb/sgb_palettes.asm)
	const_def
	const PAL_TOWNMAP2  ; $00
	const PAL_SLOTS5    ; $01
	const PAL_VIRIDIAN  ; $02
	const PAL_PEWTER    ; $03
	const PAL_CERULEAN  ; $04
	const PAL_LAVENDER  ; $05
	const PAL_VERMILION ; $06
	const PAL_CELADON   ; $07
	const PAL_FUCHSIA   ; $08
	const PAL_CINNABAR  ; $09
	const PAL_INDIGO    ; $0A
	const PAL_SAFFRON   ; $0B
	const PAL_TOWNMAP   ; $0C
	const PAL_LOGO1     ; $0D
	const PAL_LOGO2     ; $0E
	const PAL_EXP       ; $0F
	const PAL_MEWMON    ; $10
	const PAL_BLUEMON   ; $11
	const PAL_REDMON    ; $12
	const PAL_CYANMON   ; $13
	const PAL_PURPLEMON ; $14
	const PAL_BROWNMON  ; $15
	const PAL_GREENMON  ; $16
	const PAL_PINKMON   ; $17
	const PAL_YELLOWMON ; $18
	const PAL_GRAYMON   ; $19
	const PAL_SLOTS1    ; $1A
	const PAL_SLOTS2    ; $1B
	const PAL_SLOTS3    ; $1C
	const PAL_SLOTS4    ; $1D
	const PAL_BLACK     ; $1E
	const PAL_GREENBAR  ; $1F
	const PAL_YELLOWBAR ; $20
	const PAL_REDBAR    ; $21
	const PAL_BADGE     ; $22
	const PAL_CAVE      ; $23
	const PAL_GAMEFREAK ; $24

	const PAL_BULBASAUR     ; $25
	const PAL_IVYSAUR       ; $26
	const PAL_VENUSAUR      ; $27
	const PAL_CHARMANDER    ; $28
	const PAL_CHARMELEON    ; $29
	const PAL_CHARIZARD     ; $2A
	const PAL_SQUIRTLE      ; $2B
	const PAL_BLASTOISE     ; $2C
	const PAL_CATERPIE      ; $2D
	const PAL_METAPOD       ; $2E
	const PAL_BUTTERFREE    ; $2F
	const PAL_WEEDLE        ; $30
	const PAL_KAKUNA        ; $31
	const PAL_BEEDRILL      ; $32
	const PAL_PIDGEY        ; $33
	const PAL_PIDGEOTTO     ; $34
	const PAL_RATTATA       ; $35
	const PAL_RATICATE      ; $36
	const PAL_SPEAROW       ; $37
	const PAL_FEAROW        ; $38
	const PAL_EKANS         ; $39
	const PAL_ARBOK         ; $3A
	const PAL_PIKACHU       ; $3B
	const PAL_RAICHU        ; $3C
	const PAL_SANDSHREW     ; $3D
	const PAL_SANDSLASH     ; $3E
	const PAL_NIDORAN_F     ; $3F
	const PAL_NIDORINA      ; $40
	const PAL_NIDOQUEEN     ; $41
	const PAL_NIDORAN_M     ; $42
	const PAL_NIDORINO      ; $43
	const PAL_NIDOKING      ; $44
	const PAL_CLEFAIRY      ; $45
	const PAL_VULPIX        ; $46
	const PAL_NINETALES     ; $47
	const PAL_JIGGLYPUFF    ; $48
	const PAL_ZUBAT         ; $49
	const PAL_ODDISH        ; $4A
	const PAL_GLOOM         ; $4B
	const PAL_VILEPLUME     ; $4C
	const PAL_PARAS         ; $4D
	const PAL_PARASECT      ; $4E
	const PAL_VENONAT       ; $4F
	const PAL_VENOMOTH      ; $50
	const PAL_DIGLETT       ; $51
	const PAL_MEOWTH        ; $52
	const PAL_PERSIAN       ; $53
	const PAL_PSYDUCK       ; $54
	const PAL_GOLDUCK       ; $55
	const PAL_MANKEY        ; $56
	const PAL_PRIMEAPE      ; $57
	const PAL_GROWLITHE     ; $58
	const PAL_POLIWAG       ; $59
	const PAL_POLIWHIRL     ; $5A
	const PAL_POLIWRATH     ; $5B
	const PAL_ABRA          ; $5C
	const PAL_MACHOP        ; $5D
	const PAL_MACHOKE       ; $5E
	const PAL_MACHAMP       ; $5F
	const PAL_BELLSPROUT    ; $60
	const PAL_WEEPINBELL    ; $61
	const PAL_VICTREEBEL    ; $62
	const PAL_TENTACOOL     ; $63
	const PAL_TENTACRUEL    ; $64
	const PAL_GEODUDE       ; $65
	const PAL_PONYTA        ; $66
	const PAL_SLOWPOKE      ; $67
	const PAL_SLOWBRO       ; $68
	const PAL_MAGNEMITE     ; $69
	const PAL_FARFETCH_D    ; $6A
	const PAL_DODUO         ; $6B
	const PAL_DODRIO        ; $6C
	const PAL_SEEL          ; $6D
	const PAL_DEWGONG       ; $6E
	const PAL_GRIMER        ; $6F
	const PAL_SHELLDER      ; $70
	const PAL_CLOYSTER      ; $71
	const PAL_GASTLY        ; $72
	const PAL_HAUNTER       ; $73
	const PAL_GENGAR        ; $74
	const PAL_ONIX          ; $75
	const PAL_DROWZEE       ; $76
	const PAL_HYPNO         ; $77
	const PAL_KRABBY        ; $78
	const PAL_VOLTORB       ; $79
	const PAL_EXEGGCUTE     ; $7A
	const PAL_EXEGGUTOR     ; $7B
	const PAL_CUBONE        ; $7C
	const PAL_HITMONLEE     ; $7D
	const PAL_HITMONCHAN    ; $7E
	const PAL_LICKITUNG     ; $7F
	const PAL_KOFFING       ; $80
	const PAL_RHYHORN       ; $81
	const PAL_CHANSEY       ; $82
	const PAL_TANGELA       ; $83
	const PAL_KANGASKHAN    ; $84
	const PAL_HORSEA        ; $85
	const PAL_SEADRA        ; $86
	const PAL_GOLDEEN       ; $87
	const PAL_SEAKING       ; $88
	const PAL_STARYU        ; $89
	const PAL_STARMIE       ; $8A
	const PAL_MR_MIME       ; $8B
	const PAL_SCYTHER       ; $8C
	const PAL_JYNX          ; $8D
	const PAL_ELECTABUZZ    ; $8E
	const PAL_MAGMAR        ; $8F
	const PAL_PINSIR        ; $90
	const PAL_TAUROS        ; $91
	const PAL_MAGIKARP      ; $92
	const PAL_GYARADOS      ; $93
	const PAL_LAPRAS        ; $94
	const PAL_DITTO         ; $95
	const PAL_EEVEE         ; $96
	const PAL_VAPOREON      ; $97
	const PAL_JOLTEON       ; $98
	const PAL_FLAREON       ; $99
	const PAL_PORYGON       ; $9A
	const PAL_OMANYTE       ; $9B
	const PAL_KABUTO        ; $9C
	const PAL_AERODACTYL    ; $9D
	const PAL_SNORLAX       ; $9E
	const PAL_ARTICUNO      ; $9F
	const PAL_ZAPDOS        ; $A0
	const PAL_MOLTRES       ; $A1
	const PAL_DRATINI       ; $A2
	const PAL_DRAGONAIR     ; $A3
	const PAL_DRAGONITE     ; $A4
	const PAL_MEWTWO        ; $A5
	const PAL_MEW           ; $A6
	const PAL_YOUNGSTER     ; $A7
	const PAL_BUGCATCHER    ; $A8
	const PAL_LASS          ; $A9
	const PAL_SAILOR        ; $AA
	const PAL_JR_TRAINER_M  ; $AB
	const PAL_JR_TRAINER_F  ; $AC
	const PAL_POKEMANIAC    ; $AD
	const PAL_SUPERNERD     ; $AE
	const PAL_HIKER         ; $AF
	const PAL_BIKER         ; $B0
	const PAL_BURGLAR       ; $B1
	const PAL_ENGINEER      ; $B2
	const PAL_JUGGLER       ; $B3
	const PAL_FISHERMAN     ; $B4
	const PAL_SWIMMER       ; $B5
	const PAL_CUEBALL       ; $B6
	const PAL_GAMBLER       ; $B7
	const PAL_BEAUTY        ; $B8
	const PAL_PSYCHIC       ; $B9
	const PAL_ROCKER        ; $BA
	const PAL_TAMER         ; $BB
	const PAL_BIRDKEEPER    ; $BC
	const PAL_BLACKBELT     ; $BD
	const PAL_RIVAL         ; $BE
	const PAL_OAK           ; $BF
	const PAL_CHIEF         ; $C0
	const PAL_GIOVANNI      ; $C1
	const PAL_ROCKET        ; $C2
	const PAL_COOLTRAINER_M ; $C3
	const PAL_BROCK         ; $C4
	const PAL_MISTY         ; $C5
	const PAL_LT_SURGE      ; $C6
	const PAL_ERIKA         ; $C7
	const PAL_KOGA          ; $C8
	const PAL_BLAINE        ; $C9
	const PAL_SABRINA       ; $CA
	const PAL_GENTLEMAN     ; $CB
	const PAL_BLUE_TRAINER  ; $CC
	const PAL_LORELEI       ; $CD
	const PAL_CHANNELER     ; $CE
	const PAL_AGATHA        ; $CF
	const PAL_LANCE         ; $D0
	const PAL_HERO          ; $D1
	const PAL_UMBREON       ; $D2
	const PAL_ESPEON        ; $D3
	const PAL_SYLVEON       ; $D4
	const PAL_MISDREAVUS    ; $D5
	const PAL_SCIZOR        ; $D6
	const PAL_STEELIX       ; $D7
	const PAL_BELLOSSOM     ; $D8
	const PAL_DUNSPARCE     ; $D9
	const PAL_WOOPER        ; $DA
	const PAL_QUAGSIRE      ; $DB
	const PAL_PALWOOPER     ; $DC
	const PAL_CLODSIRE      ; $DD
	const PAL_IONO          ; $DE
	const PAL_N             ; $DF
	const PAL_CYNTHIA       ; $E0
	const PAL_JACINTHE      ; $E1
	const PAL_MAREEP        ; $E2
	const PAL_FLAAFFY       ; $E3
	const PAL_AMPHAROS      ; $E4
	const PAL_LEDYBA        ; $E5
	const PAL_HOOPA         ; $E6
	const PAL_SKARMORY      ; $E7
	const PAL_MILTANK       ; $E8
	const PAL_PINECO        ; $E9
	const PAL_FORRETRESS    ; $EA
	const PAL_POLITOED      ; $EB
	const PAL_SLOWKING      ; $EC
	const PAL_MAGBY         ; $ED
	const PAL_TYROGUE       ; $EE
	const PAL_ELEKID        ; $EF
	const PAL_SMOOCHUM      ; $F0
	const PAL_HITMONTOP     ; $F1
	const PAL_KINGDRA       ; $F2
	const PAL_BLISSEY       ; $F3
	const PAL_PORYGON2      ; $F4
	const PAL_WHITNEY       ; $F5
	const PAL_RED           ; $F6
	const PAL_MARNIE        ; $F7
	const PAL_HOUNDOUR      ; $F8
	const PAL_HOUNDOOM      ; $F9
DEF NUM_SGB_PALS EQU const_value
