; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_IGGLYBUFF      ; 1
	const DEX_JIGGLYPUFF     ; 2
	const DEX_WIGGLYTUFF     ; 3
	const DEX_MAGNEMITE      ; 4
	const DEX_MAGNETON       ; 5
	const DEX_MAGNEZONE      ; 6
	const DEX_DRATINI        ; 7
	const DEX_DRAGONAIR      ; 8
	const DEX_DRAGONITE      ; 9
	const DEX_CATERPIE       ; 10
	const DEX_METAPOD        ; 11
	const DEX_BUTTERFREE     ; 12
	const DEX_WEEDLE         ; 13
	const DEX_KAKUNA         ; 14
	const DEX_BEEDRILL       ; 15
	const DEX_LEDYBA         ; 16
	const DEX_LEDIAN         ; 17
	const DEX_PINECO         ; 18
	const DEX_FORRETRESS     ; 19
	const DEX_PIDGEY         ; 20
	const DEX_PIDGEOTTO      ; 21
	const DEX_PIDGEOT        ; 22
	const DEX_RATTATA        ; 23
	const DEX_RATICATE       ; 24
	const DEX_SPEAROW        ; 25
	const DEX_FEAROW         ; 26
	const DEX_EKANS          ; 27
	const DEX_ARBOK          ; 28
	const DEX_PICHU          ; 29
	const DEX_PIKACHU        ; 30
	const DEX_RAICHU         ; 31
	const DEX_SANDSHREW      ; 32
	const DEX_SANDSLASH      ; 33
	const DEX_NIDORAN_F      ; 34
	const DEX_NIDORINA       ; 35
	const DEX_NIDOQUEEN      ; 36
	const DEX_NIDORAN_M      ; 37
	const DEX_NIDORINO       ; 38
	const DEX_NIDOKING       ; 39
	const DEX_CLEFFA         ; 40
	const DEX_CLEFAIRY       ; 41
	const DEX_CLEFABLE       ; 42
	const DEX_VULPIX         ; 43
	const DEX_NINETALES      ; 44
	const DEX_ZUBAT          ; 45
	const DEX_GOLBAT         ; 46
	const DEX_CROBAT         ; 47
	const DEX_ODDISH         ; 48
	const DEX_GLOOM          ; 49
	const DEX_VILEPLUME      ; 50
	const DEX_BELLOSSOM      ; 51
	const DEX_PARAS          ; 52
	const DEX_PARASECT       ; 53
	const DEX_VENONAT        ; 54
	const DEX_VENOMOTH       ; 55
	const DEX_DIGLETT        ; 56
	const DEX_DUGTRIO        ; 57
	const DEX_MEOWTH         ; 58
	const DEX_PERSIAN        ; 59
	const DEX_PSYDUCK        ; 60
	const DEX_GOLDUCK        ; 61
	const DEX_MANKEY         ; 62
	const DEX_PRIMEAPE       ; 63
	const DEX_GROWLITHE      ; 64
	const DEX_ARCANINE       ; 65
	const DEX_POLIWAG        ; 66
	const DEX_POLIWHIRL      ; 67
	const DEX_POLIWRATH      ; 68
	const DEX_POLITOED       ; 69
	const DEX_WOOPER         ; 70
	const DEX_QUAGSIRE       ; 71
	const DEX_PALDEAN_WOOPER ; 72
	const DEX_CLODSIRE       ; 73
	const DEX_ABRA           ; 74
	const DEX_KADABRA        ; 75
	const DEX_ALAKAZAM       ; 76
	const DEX_MACHOP         ; 77
	const DEX_MACHOKE        ; 78
	const DEX_MACHAMP        ; 79
	const DEX_BELLSPROUT     ; 80
	const DEX_WEEPINBELL     ; 81
	const DEX_VICTREEBEL     ; 82
	const DEX_TENTACOOL      ; 83
	const DEX_TENTACRUEL     ; 84
	const DEX_GEODUDE        ; 85
	const DEX_GRAVELER       ; 86
	const DEX_GOLEM          ; 87
	const DEX_PONYTA         ; 88
	const DEX_RAPIDASH       ; 89
	const DEX_SLOWPOKE       ; 90
	const DEX_SLOWBRO        ; 91
	const DEX_SLOWKING       ; 92
	const DEX_FARFETCHD      ; 93
	const DEX_DODUO          ; 94
	const DEX_DODRIO         ; 95
	const DEX_SEEL           ; 96
	const DEX_DEWGONG        ; 97
	const DEX_GRIMER         ; 98
	const DEX_MUK            ; 99
	const DEX_HOUNDOUR       ; 100
	const DEX_HOUNDOOM       ; 101
	const DEX_SHELLDER       ; 102
	const DEX_CLOYSTER       ; 103
	const DEX_GASTLY         ; 104
	const DEX_HAUNTER        ; 105
	const DEX_GENGAR         ; 106
	const DEX_MISDREAVUS     ; 107
	const DEX_ONIX           ; 108
	const DEX_STEELIX        ; 109
	const DEX_DROWZEE        ; 110
	const DEX_HYPNO          ; 111
	const DEX_KRABBY         ; 112
	const DEX_KINGLER        ; 113
	const DEX_VOLTORB        ; 114
	const DEX_ELECTRODE      ; 115
	const DEX_EXEGGCUTE      ; 116
	const DEX_EXEGGUTOR      ; 117
	const DEX_CUBONE         ; 118
	const DEX_MAROWAK        ; 119
	const DEX_TYROGUE        ; 120
	const DEX_HITMONLEE      ; 121
	const DEX_HITMONCHAN     ; 122
	const DEX_HITMONTOP      ; 123
	const DEX_LICKITUNG      ; 124
	const DEX_KOFFING        ; 125
	const DEX_WEEZING        ; 126
	const DEX_RHYHORN        ; 127
	const DEX_RHYDON         ; 128
	const DEX_CHANSEY        ; 129
	const DEX_BLISSEY        ; 130
	const DEX_TANGELA        ; 131
	const DEX_KANGASKHAN     ; 132
	const DEX_HORSEA         ; 133
	const DEX_SEADRA         ; 134
	const DEX_KINGDRA        ; 135
	const DEX_GOLDEEN        ; 136
	const DEX_SEAKING        ; 137
	const DEX_STARYU         ; 138
	const DEX_STARMIE        ; 139
	const DEX_DUNSPARCE      ; 140
	const DEX_MR_MIME        ; 141
	const DEX_SCYTHER        ; 142
	const DEX_SCIZOR         ; 143
	const DEX_SMOOCHUM       ; 144
	const DEX_JYNX           ; 145
	const DEX_ELEKID         ; 146
	const DEX_ELECTABUZZ     ; 147
	const DEX_MAGBY          ; 148
	const DEX_MAGMAR         ; 149
	const DEX_PINSIR         ; 150
	const DEX_SKARMORY       ; 151
	const DEX_TAUROS         ; 152
	const DEX_MILTANK        ; 153
	const DEX_MAGIKARP       ; 154
	const DEX_GYARADOS       ; 155
	const DEX_LAPRAS         ; 156
	const DEX_DITTO          ; 157
	const DEX_EEVEE          ; 158
	const DEX_VAPOREON       ; 159
	const DEX_JOLTEON        ; 160
	const DEX_FLAREON        ; 161
	const DEX_ESPEON         ; 162
	const DEX_UMBREON        ; 163
	const DEX_SYLVEON        ; 164
	const DEX_PORYGON        ; 165
	const DEX_PORYGON2       ; 166
	const DEX_OMANYTE        ; 167
	const DEX_OMASTAR        ; 168
	const DEX_KABUTO         ; 169
	const DEX_KABUTOPS       ; 170
	const DEX_AERODACTYL     ; 171
	const DEX_SNORLAX        ; 172
	const DEX_MAREEP         ; 173
	const DEX_FLAAFFY        ; 174
	const DEX_AMPHAROS       ; 175
	const DEX_ARTICUNO       ; 176
	const DEX_ZAPDOS         ; 177
	const DEX_MOLTRES        ; 178
	const DEX_BULBASAUR      ; 179
	const DEX_IVYSAUR        ; 180
	const DEX_VENUSAUR       ; 181
	const DEX_CHARMANDER     ; 182
	const DEX_CHARMELEON     ; 183
	const DEX_CHARIZARD      ; 184
	const DEX_SQUIRTLE       ; 185
	const DEX_WARTORTLE      ; 186
	const DEX_BLASTOISE      ; 187
	const DEX_MEWTWO         ; 188
	const DEX_MEW            ; 189
	const DEX_HOOPA          ; 190

DEF NUM_POKEMON EQU const_value - 1
