SECTION "Pics 1", ROMX

MoltresPicFront::    INCBIN "gfx/pokemon/gsfront/moltres.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/gsback/moltresb.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/gsfront/tentacool.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/gsback/tentacoolb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/gsfront/scyther.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/gsback/scytherb.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/gsfront/staryu.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/gsback/staryub.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/gsfront/blastoise.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/gsback/blastoiseb.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/gsfront/pinsir.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/gsback/pinsirb.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/gsfront/tangela.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/gsback/tangelab.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/gsfront/jolteon.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/gsback/jolteonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/gsfront/vaporeon.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/gsback/vaporeonb.pic"
MachopPicFront::     INCBIN "gfx/pokemon/gsfront/machop.pic"
MachopPicBack::      INCBIN "gfx/pokemon/gsback/machopb.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/gsfront/zubat.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/gsback/zubatb.pic"
EkansPicFront::      INCBIN "gfx/pokemon/gsfront/ekans.pic"
EkansPicBack::       INCBIN "gfx/pokemon/gsback/ekansb.pic"
ParasPicFront::      INCBIN "gfx/pokemon/gsfront/paras.pic"
ParasPicBack::       INCBIN "gfx/pokemon/gsback/parasb.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/gsfront/poliwhirl.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/gsback/poliwhirlb.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/gsfront/poliwrath.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/gsback/poliwrathb.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/gsfront/weedle.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/gsback/weedleb.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/gsfront/kakuna.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/gsback/kakunab.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/gsfront/beedrill.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/gsback/beedrillb.pic"


SECTION "Pics 2", ROMX

HaunterPicFront::    INCBIN "gfx/pokemon/gsfront/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/gsback/haunterb.pic"
AbraPicFront::       INCBIN "gfx/pokemon/gsfront/abra.pic"
AbraPicBack::        INCBIN "gfx/pokemon/gsback/abrab.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/gsfront/alakazam.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/gsback/alakazamb.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/gsfront/pidgeotto.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/gsback/pidgeottob.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/gsfront/pidgeot.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/gsback/pidgeotb.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/gsfront/starmie.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/gsback/starmieb.pic"
RedPicBack::         INCBIN "gfx/gstrainers/redb.pic"
OldManPicBack::      INCBIN "gfx/gstrainers/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/gsfront/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/gsback/gastlyb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/gsfront/vileplume.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/gsback/vileplumeb.pic"


SECTION "Pics 3", ROMX

; Removed 'mon sprites from here


SECTION "Pics 4", ROMX

; Removed 'mon sprites from here


SECTION "Pics 5", ROMX

; Removed 'mon sprites from here


SECTION "Trainer Pics", ROMX

TrainerPics::
YoungsterPic::     INCBIN "gfx/gstrainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/gstrainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/gstrainers/lass.pic"
SailorPic::        INCBIN "gfx/gstrainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/gstrainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/gstrainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/gstrainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/gstrainers/supernerd.pic"
HikerPic::         INCBIN "gfx/gstrainers/hiker.pic"
BikerPic::         INCBIN "gfx/gstrainers/biker.pic"
BurglarPic::       INCBIN "gfx/gstrainers/burglar.pic"
EngineerPic::      INCBIN "gfx/gstrainers/engineer.pic"
FisherPic::        INCBIN "gfx/gstrainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/gstrainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/gstrainers/cueball.pic"
GamblerPic::       INCBIN "gfx/gstrainers/gambler.pic"
BeautyPic::        INCBIN "gfx/gstrainers/beauty.pic"
PsychicPic::       INCBIN "gfx/gstrainers/psychic.pic"
RockerPic::        INCBIN "gfx/gstrainers/rocker.pic"
JugglerPic::       INCBIN "gfx/gstrainers/juggler.pic"
TamerPic::         INCBIN "gfx/gstrainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/gstrainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/gstrainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/gstrainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/gstrainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/gstrainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/gstrainers/giovanni.pic"
RocketPic::        INCBIN "gfx/gstrainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/gstrainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/gstrainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/gstrainers/bruno.pic"
BrockPic::         INCBIN "gfx/gstrainers/brock.pic"
MistyPic::         INCBIN "gfx/gstrainers/misty.pic"
LtSurgePic::       INCBIN "gfx/gstrainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/gstrainers/erika.pic"
KogaPic::          INCBIN "gfx/gstrainers/koga.pic"
BlainePic::        INCBIN "gfx/gstrainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/gstrainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/gstrainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/gstrainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/gstrainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/gstrainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/gstrainers/channeler.pic"
AgathaPic::        INCBIN "gfx/gstrainers/agatha.pic"
LancePic::         INCBIN "gfx/gstrainers/lance.pic"


; Inserted pokemon images go here

SECTION "Pics 7", ROMX

IgglybuffPicFront::   INCBIN "gfx/pokemon/gsfront/igglybuff.pic"
IgglybuffPicBack::    INCBIN "gfx/pokemon/gsback/igglybuffb.pic"
MagnezonePicFront::   INCBIN "gfx/pokemon/gsfront/magnezone.pic"
MagnezonePicBack::    INCBIN "gfx/pokemon/gsback/magnezoneb.pic"
GrowlithePicFront::   INCBIN "gfx/pokemon/gsfront/growlithe.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/gsback/growlitheb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/gsfront/onix.pic"
OnixPicBack::         INCBIN "gfx/pokemon/gsback/onixb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/gsfront/fearow.pic"
FearowPicBack::       INCBIN "gfx/pokemon/gsback/fearowb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/gsfront/pidgey.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/gsback/pidgeyb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/gsfront/slowpoke.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/gsback/slowpokeb.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/gsfront/kadabra.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/gsback/kadabrab.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/gsfront/graveler.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/gsback/gravelerb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/gsfront/chansey.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/gsback/chanseyb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/gsfront/machoke.pic"
MachokePicBack::      INCBIN "gfx/pokemon/gsback/machokeb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/gsfront/mr.mime.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/gsback/mr.mimeb.pic"
HitmonleePicFront::   INCBIN "gfx/pokemon/gsfront/hitmonlee.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/gsback/hitmonleeb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/gsfront/hitmonchan.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/gsback/hitmonchanb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/gsfront/arbok.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/gsback/arbokb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/gsfront/parasect.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/gsback/parasectb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/gsfront/psyduck.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/gsback/psyduckb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/gsfront/drowzee.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/gsback/drowzeeb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/gsfront/golem.pic"
GolemPicBack::        INCBIN "gfx/pokemon/gsback/golemb.pic"
EspeonPicFront::      INCBIN "gfx/pokemon/gsfront/espeon.pic"
EspeonPicBack::       INCBIN "gfx/pokemon/gsback/espeonb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/gsfront/magmar.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/gsback/magmarb.pic"
UmbreonPicFront::     INCBIN "gfx/pokemon/gsfront/umbreon.pic"
UmbreonPicBack::      INCBIN "gfx/pokemon/gsback/umbreonb.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/gsfront/electabuzz.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/gsback/electabuzzb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/gsfront/magneton.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/gsback/magnetonb.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/gsfront/koffing.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/gsback/koffingb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/gsfront/mankey.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/gsback/mankeyb.pic"

SECTION "Pics 8", ROMX

SeelPicFront::        INCBIN "gfx/pokemon/gsfront/seel.pic"
SeelPicBack::         INCBIN "gfx/pokemon/gsback/seelb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/gsfront/diglett.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/gsback/diglettb.pic"
TaurosPicFront::      INCBIN "gfx/pokemon/gsfront/tauros.pic"
TaurosPicBack::       INCBIN "gfx/pokemon/gsback/taurosb.pic"
RhydonPicFront::      INCBIN "gfx/pokemon/gsfront/rhydon.pic"
RhydonPicBack::       INCBIN "gfx/pokemon/gsback/rhydonb.pic"
KangaskhanPicFront::  INCBIN "gfx/pokemon/gsfront/kangaskhan.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/gsback/kangaskhanb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/gsfront/nidoranm.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/gsback/nidoranmb.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/gsfront/clefairy.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/gsback/clefairyb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/gsfront/spearow.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/gsback/spearowb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/gsfront/voltorb.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/gsback/voltorbb.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/gsfront/nidoking.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/gsback/nidokingb.pic"
SlowbroPicFront::     INCBIN "gfx/pokemon/gsfront/slowbro.pic"
SlowbroPicBack::      INCBIN "gfx/pokemon/gsback/slowbrob.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/gsfront/ivysaur.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/gsback/ivysaurb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/gsfront/exeggutor.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/gsback/exeggutorb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/gsfront/lickitung.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/gsback/lickitungb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/gsfront/exeggcute.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/gsback/exeggcuteb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/gsfront/grimer.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/gsback/grimerb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/gsfront/gengar.pic"
GengarPicBack::       INCBIN "gfx/pokemon/gsback/gengarb.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/gsfront/nidoranf.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/gsback/nidoranfb.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/gsfront/nidoqueen.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/gsback/nidoqueenb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/gsfront/cubone.pic"
CubonePicBack::       INCBIN "gfx/pokemon/gsback/cuboneb.pic"
RhyhornPicFront::     INCBIN "gfx/pokemon/gsfront/rhyhorn.pic"
RhyhornPicBack::      INCBIN "gfx/pokemon/gsback/rhyhornb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/gsfront/lapras.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/gsback/laprasb.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/gsfront/arcanine.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/gsback/arcanineb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/gsfront/gyarados.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/gsback/gyaradosb.pic"


SECTION "Pics 9", ROMX

ShellderPicFront::    INCBIN "gfx/pokemon/gsfront/shellder.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/gsback/shellderb.pic"
ArticunoPicFront::    INCBIN "gfx/pokemon/gsfront/articuno.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/gsback/articunob.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/gsfront/zapdos.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/gsback/zapdosb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/gsfront/ditto.pic"
DittoPicBack::        INCBIN "gfx/pokemon/gsback/dittob.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/gsfront/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/gsback/meowthb.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/gsfront/krabby.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/gsback/krabbyb.pic"
PichuPicFront::      INCBIN "gfx/pokemon/gsfront/pichu.pic"
PichuPicBack::       INCBIN "gfx/pokemon/gsback/pichub.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/gsfront/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/gsback/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/gsfront/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/gsback/ninetalesb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/gsfront/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/gsback/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/gsfront/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/gsback/raichub.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/gsfront/dratini.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/gsback/dratinib.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/gsfront/dragonair.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/gsback/dragonairb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/gsfront/kabuto.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/gsback/kabutob.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/gsfront/kabutops.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/gsback/kabutopsb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/gsfront/horsea.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/gsback/horseab.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/gsfront/seadra.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/gsback/seadrab.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/gsfront/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/gsback/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/gsfront/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/gsback/sandslashb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/gsfront/omanyte.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/gsback/omanyteb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/gsfront/omastar.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/gsback/omastarb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/gsfront/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/gsback/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/gsfront/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/gsback/wigglytuffb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/gsfront/eevee.pic"
EeveePicBack::        INCBIN "gfx/pokemon/gsback/eeveeb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/gsfront/flareon.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/gsback/flareonb.pic"


SECTION "Pics 10", ROMX

DodrioPicFront::      INCBIN "gfx/pokemon/gsfront/dodrio.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/gsback/dodriob.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/gsfront/primeape.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/gsback/primeapeb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/gsfront/dugtrio.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/gsback/dugtriob.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/gsfront/venomoth.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/gsback/venomothb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/gsfront/dewgong.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/gsback/dewgongb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/gsfront/caterpie.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/gsback/caterpieb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/gsfront/metapod.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/gsback/metapodb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/gsfront/butterfree.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/gsback/butterfreeb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/gsfront/machamp.pic"
MachampPicBack::      INCBIN "gfx/pokemon/gsback/machampb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/gsfront/golduck.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/gsback/golduckb.pic"
HypnoPicFront::       INCBIN "gfx/pokemon/gsfront/hypno.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/gsback/hypnob.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/gsfront/golbat.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/gsback/golbatb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/gsfront/mewtwo.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/gsback/mewtwob.pic"
SnorlaxPicFront::     INCBIN "gfx/pokemon/gsfront/snorlax.pic"
SnorlaxPicBack::      INCBIN "gfx/pokemon/gsback/snorlaxb.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/gsfront/magikarp.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/gsback/magikarpb.pic"
MukPicFront::         INCBIN "gfx/pokemon/gsfront/muk.pic"
MukPicBack::          INCBIN "gfx/pokemon/gsback/mukb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/gsfront/kingler.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/gsback/kinglerb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/gsfront/cloyster.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/gsback/cloysterb.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/gsfront/electrode.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/gsback/electrodeb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/gsfront/clefable.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/gsback/clefableb.pic"
WeezingPicFront::     INCBIN "gfx/pokemon/gsfront/weezing.pic"
WeezingPicBack::      INCBIN "gfx/pokemon/gsback/weezingb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/gsfront/persian.pic"
PersianPicBack::      INCBIN "gfx/pokemon/gsback/persianb.pic"


SECTION "Pics 11", ROMX

BulbasaurPicFront::   INCBIN "gfx/pokemon/gsfront/bulbasaur.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/gsback/bulbasaurb.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/gsfront/venusaur.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/gsback/venusaurb.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/gsfront/tentacruel.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/gsback/tentacruelb.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/gsfront/goldeen.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/gsback/goldeenb.pic"
SeakingPicFront::     INCBIN "gfx/pokemon/gsfront/seaking.pic"
SeakingPicBack::      INCBIN "gfx/pokemon/gsback/seakingb.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/gsfront/ponyta.pic"
RapidashPicFront::    INCBIN "gfx/pokemon/gsfront/rapidash.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/gsback/ponytab.pic"
RapidashPicBack::     INCBIN "gfx/pokemon/gsback/rapidashb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/gsfront/rattata.pic"
RattataPicBack::      INCBIN "gfx/pokemon/gsback/rattatab.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/gsfront/raticate.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/gsback/raticateb.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/gsfront/nidorino.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/gsback/nidorinob.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/gsfront/nidorina.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/gsback/nidorinab.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/gsfront/geodude.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/gsback/geodudeb.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/gsfront/porygon.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/gsback/porygonb.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/gsfront/aerodactyl.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/gsback/aerodactylb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/gsfront/magnemite.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/gsback/magnemiteb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/gsfront/charmander.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/gsback/charmanderb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/gsfront/squirtle.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/gsback/squirtleb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/gsfront/charmeleon.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/gsback/charmeleonb.pic"
WartortlePicFront::   INCBIN "gfx/pokemon/gsfront/wartortle.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/gsback/wartortleb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/gsfront/charizard.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/gsback/charizardb.pic"
FossilKabutopsPic::   INCBIN "gfx/pokemon/gsfront/fossilkabutops.pic"
FossilAerodactylPic:: INCBIN "gfx/pokemon/gsfront/fossilaerodactyl.pic"
GhostPic::            INCBIN "gfx/battle/ghost.pic"
OddishPicFront::      INCBIN "gfx/pokemon/gsfront/oddish.pic"
OddishPicBack::       INCBIN "gfx/pokemon/gsback/oddishb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/gsfront/gloom.pic"
GloomPicBack::        INCBIN "gfx/pokemon/gsback/gloomb.pic"

SECTION "Pics 12", ROMX

BellsproutPicFront::  INCBIN "gfx/pokemon/gsfront/bellsprout.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/gsback/bellsproutb.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/gsfront/weepinbell.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/gsback/weepinbellb.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/gsfront/victreebel.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/gsback/victreebelb.pic"

MewPicFront::         INCBIN "gfx/pokemon/gsfront/mew.pic"
MewPicBack::          INCBIN "gfx/pokemon/gsback/mewb.pic"

FarfetchdPicFront::   INCBIN "gfx/pokemon/gsfront/farfetchd.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/gsback/farfetchdb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/gsfront/venonat.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/gsback/venonatb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/gsfront/dragonite.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/gsback/dragoniteb.pic"
SylveonPicFront::     INCBIN "gfx/pokemon/gsfront/sylveon.pic"
SylveonPicBack::      INCBIN "gfx/pokemon/gsback/sylveonb.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/gsfront/doduo.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/gsback/doduob.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/gsfront/poliwag.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/gsback/poliwagb.pic"
JynxPicFront::        INCBIN "gfx/pokemon/gsfront/jynx.pic"
JynxPicBack::         INCBIN "gfx/pokemon/gsback/jynxb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/gsfront/marowak.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/gsback/marowakb.pic"
MisdreavusPicFront::  INCBIN "gfx/pokemon/gsfront/misdreavus.pic"
MisdreavusPicBack::   INCBIN "gfx/pokemon/gsback/misdreavusb.pic"
ScizorPicFront::      INCBIN "gfx/pokemon/gsfront/scizor.pic"
ScizorPicBack::       INCBIN "gfx/pokemon/gsback/scizorb.pic"
SteelixPicFront::     INCBIN "gfx/pokemon/gsfront/steelix.pic"
SteelixPicBack::      INCBIN "gfx/pokemon/gsback/steelixb.pic"
CrobatPicFront::      INCBIN "gfx/pokemon/gsfront/crobat.pic"
CrobatPicBack::       INCBIN "gfx/pokemon/gsback/crobatb.pic"
BellossomPicFront::   INCBIN "gfx/pokemon/gsfront/bellossom.pic"
BellossomPicBack::    INCBIN "gfx/pokemon/gsback/bellossomb.pic"
DunsparcePicFront::   INCBIN "gfx/pokemon/gsfront/dunsparce.pic"
DunsparcePicBack::    INCBIN "gfx/pokemon/gsback/dunsparceb.pic"
CleffaPicFront::      INCBIN "gfx/pokemon/gsfront/cleffa.pic"
CleffaPicBack::       INCBIN "gfx/pokemon/gsback/cleffab.pic"
